Database:
  postgres:
    Host: localhost
    Port: 5432
    Database: zitadel
    EventPushConnRatio: 0.2
    MaxOpenConns: 40
    MaxIdleConns: 10
    User:
      Username: zitadel
      SSL:
        Mode: disable
    Admin:
      Username: zitadel
      SSL:
        Mode: disable
