# Generated by Django 3.2.9 on 2022-01-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_checklist_testing2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='testing2',
            new_name='is_todays_bath',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='testing',
        ),
        migrations.RemoveField(
            model_name='checklist',
            name='testing1',
        ),
        migrations.AddField(
            model_name='checklist',
            name='today_date_temporary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
