name: 🔀 Sync mirror to Gitee

on:
  push:
    branches:
      - master
      - gh-pages
      - feature
      - 2.x-stable
      - 3.x-stable
      - 4.x-stable
  create:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  mirror:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    if: github.repository == 'ant-design/ant-design'
    steps:
      - name: mirror
        continue-on-error: true
        if: github.event_name == 'push' || (github.event_name == 'create' && github.event.ref_type == 'tag') || github.event_name == 'workflow_dispatch'
        uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
        with:
          source-repo: 'git@github.com:ant-design/ant-design.git'
          destination-repo: 'git@gitee.com:ant-design/ant-design.git'
