[package]
name = "turborepo-lib"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[features]
# Allows configuring a specific tls backend for reqwest.
# See top level Cargo.toml for more details.
default = ["rustls-tls"]
native-tls = ["turborepo-api-client/native-tls", "turbo-updater/native-tls"]
rustls-tls = ["turborepo-api-client/rustls-tls", "turbo-updater/rustls-tls"]

# serve the daemon over a port (useful for testing)
http = ["tonic-reflection"]

go-daemon = []
daemon-package-discovery = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dev-dependencies]
anyhow = { workspace = true, features = ["backtrace"] }
assert_cmd = { workspace = true }
async-stream = "0.3.4"
itertools = { workspace = true }
port_scanner = { workspace = true }
pretty_assertions = { workspace = true }
tempdir = "0.3.7"
tempfile = { workspace = true }
test-case = { workspace = true }
tracing-test = { version = "0.2.4", features = ["no-env-filter"] }
tracing.workspace = true
turborepo-vercel-api-mock = { workspace = true }

[lints]
workspace = true

[dependencies]
atty = { workspace = true }
axum = { workspace = true }
axum-server = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
clap = { workspace = true, features = ["derive", "env"] }
clap_complete = { workspace = true }
command-group = { version = "2.1.0", features = ["with-tokio"] }
console = { workspace = true }
crossterm = "0.26"
ctrlc = { version = "3.4.0", features = ["termination"] }
dialoguer = { workspace = true, features = ["fuzzy-select"] }
directories = "4.0.1"
dirs-next = "2.0.0"
dunce = { workspace = true }
futures = "0.3.26"
globwatch = { path = "../turborepo-globwatch" }
hex = "0.4.3"
hostname = "0.3.1"
humantime = "2.1.0"
indicatif = { workspace = true }
itertools = { workspace = true }
json_comments = "0.2.1"
jsonc-parser = { version = "0.21.0" }
lazy_static = { workspace = true }
libc = "0.2.140"
nix = "0.26.2"
notify = { workspace = true }
path-clean = "1.0.1"
petgraph = { workspace = true }
pidlock = { path = "../turborepo-pidlock" }
portable-pty = "0.8.1"
prost = "0.12.3"
rand = { workspace = true }
reqwest = { workspace = true, default-features = false, features = ["json"] }
rustc_version_runtime = "0.2.1"
semver = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
sha2 = { workspace = true }
shared_child = "1.0.0"
sysinfo = "0.27.7"
thiserror = "1.0.38"
time = "0.3.20"
tiny-gradient = { workspace = true }
tokio = { workspace = true, features = ["full", "time"] }
tokio-stream = { version = "0.1.12", features = ["net"] }
tokio-util = { version = "0.7.7", features = ["compat"] }
tonic = { version = "0.11.0", features = ["transport"] }
tonic-reflection = { version = "0.11.0", optional = true }
tower = "0.4.13"
turborepo-analytics = { path = "../turborepo-analytics" }
turborepo-auth = { path = "../turborepo-auth" }
turborepo-dirs = { path = "../turborepo-dirs" }

turborepo-fs = { path = "../turborepo-fs" }
turborepo-graph-utils = { path = "../turborepo-graph-utils" }
turborepo-repository = { path = "../turborepo-repository" }
turborepo-vercel-api = { path = "../turborepo-vercel-api" }
uds_windows = "1.0.2"
url = "2.3.1"

biome_console = { workspace = true }
biome_deserialize = { workspace = true }
biome_diagnostics = { workspace = true }
biome_json_parser = { workspace = true }
biome_json_syntax = { workspace = true }

camino = "1.1.4"
capnp = "0.17.2"
const_format = "0.2.30"
convert_case = "0.6.0"
globwalk = { version = "0.1.0", path = "../turborepo-globwalk" }
go-parse-duration = "0.1.1"
is-terminal = "0.4.7"
lazy-regex = "2.5.0"
miette = { workspace = true, features = ["fancy"] }
node-semver = "2.1.0"
num_cpus = "1.15.0"
owo-colors.workspace = true
pprof = { version = "0.12.1", features = [
  "prost-codec",
  "frame-pointer",
], optional = true }
rayon = "1.7.0"
regex.workspace = true
struct_iterable = "0.1.1"
svix-ksuid = { version = "0.7.0", features = ["serde"] }
tabwriter = "1.3.0"
tracing-appender = "0.2.2"
tracing-chrome = "0.7.1"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
tracing.workspace = true
turbo-updater = { workspace = true }
turbopath = { workspace = true }
turborepo-api-client = { workspace = true }
turborepo-cache = { workspace = true }
turborepo-ci = { workspace = true }
turborepo-env = { workspace = true }
turborepo-errors = { workspace = true }
turborepo-filewatch = { path = "../turborepo-filewatch" }
turborepo-lockfiles = { workspace = true }
turborepo-scm = { workspace = true }
turborepo-telemetry = { path = "../turborepo-telemetry" }
turborepo-ui = { workspace = true }
twox-hash = "1.6.3"
wax = { workspace = true }
webbrowser = { workspace = true }
which = { workspace = true }


[target.'cfg(target_os = "windows")'.dependencies]
uds_windows = "1.0.2"
async-io = "1.12.0"

[target.'cfg(target_os = "windows")'.dev-dependencies]
winapi = "0.3.9"

[build-dependencies]
capnpc = "0.18.0"
tonic-build = "0.8.4"
