tasks:
  - name: git
    before: |
      echo "Hello Programmer, thanks for using better."
    init: |
      git pull
    command: |
      git status
  - name: rust
    before: |
      cd rust
    init: |
      echo "export RUSTUP_INIT_SKIP_KEYRING=yes" >> ~/.bashrc
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh && . "$HOME/.cargo/env"
    command: |
      rustc --version && cargo --version
