const SOURCES = [
  // High important
  "better",
  // "snippets-mate",
  // "testing",
  // "dx-beta",
  // "dx-new-experiment",
  // "dx-new",
  // "dx-experiment",
  // "dx-latest",
  // "dx-depricated",
  // "Vivo-y20",
  // "Pro-Component",
  // "Test",
  // "Pendings",



  // "dx",
  // "snippets-mate",
  // "testing",
  // "dx-new-experiment",
  // "dx-new",
  // "dx-experiment",
  // "dx-latest",
  // "Vivo-y20",
  // "Pro-Component",
  // "Test",
  // "Pendings",
  // "dx-beta",
  // "dx-depricated",

  // Medium Important
  // "op",
  // "seyanet",
  // "seyaha-net-marketplace",
  // "xstream-website",
  // "xstream-dev-space",
  // "Jrzy",
  // "Cryto-Dragons",
  // "Flag-Network",
  // "Gung-Gang",
  // "youtube-automation",
  // "feild-manager-project",
  // "people-per-hour-project",
  // "Bitpanda",
  // "field-manager",
  // "Aladdin-template",
  // "Metaplex",
  // "Candy-machine",
  // "Doraemon",
  // "flutter",
  // "Metaplex-Store",

  // Low Important
  // "snap-project",
  // "llama3",
  // "Solana-cli",
  // "Aladdin-Template-1o1",
  // "Moralis-boilerplate",
  // "Aladdin-Template1o1",
  // "Nft-collections",
  // "must-be-polygon",
  // "Ninja",
  // "mint-polygon",
  // "Mint",
  // "Metaplex-candy",
  // "Solana",
  // "Pancake",
  // "Demo1o1",
  // "with-redux",
  // "Demo",
  // "React_Social_Login-Template"
];
