version: '3.8'

services:
  zitadel:
    extends:
      file: './config/localhost/docker-compose.yaml'
      service: 'zitadel'

  db:
    extends:
      file: './config/localhost/docker-compose.yaml'
      service: 'db'
