import Link from 'next/link'
import Script from 'next/script'
import Head from 'next/head'
import Image from 'next/image'
// import img from 'next/img'









export default function Home_page(){
  return (
    <>
        
      


          
        <div id="intropage">
          <Image src="/bck.png" alt="hi" id="intro-bg" height={1000} width={1000} />
          <div id="intropage-main">
            <div id="intropage-top">
              <div id="intro">
                <h1 className="op-bg-tx main-intro">Welcome to EtherSwap</h1>
                <h6 className="text-muted intro-extra">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatibus voluptas cupiditate unde neque perferendis eaque nisi nihil nulla. Quisquam veritatis iusto eveniet non tenetur porro, deserunt laboriosam. Beatae, facere, fugiat?</h6>
              </div>
              <div id="intro-btns">
                <div id="int-btn2" className="btn btn-white"> Buy Etherium</div>
                <div id="int-btn1" className="btn btn-white"> Learn more </div>
              </div>
            </div>
            <div id="intropage-center">
              <div id="testimonials">
                <div id="privacy">
                  <ion-icon name="finger-print-outline" />
                  <h3>Privacy is must in here!</h3>
                </div>
                <div id="refresh">
                  <ion-icon name="refresh-outline" />
                  <h3>Refresh start</h3>
                </div>
                <div id="eterium">
                  <ion-icon name="hand-left-outline" />
                  <h3>Etheriam</h3>
                </div>
                <div id="terms">
                  <ion-icon name="hand-left-outline" />
                  <h3>Terms and conditions</h3>
                </div>
              </div>
            </div>
            <div id="intropage-bottom">
              <div id="trades">
                <div className="trade">
                  <h1>hi</h1>
                </div>
                <div id="trade1" className="trade">
                  <h6> trade1 </h6>
                </div>
                <div id="trade2" className="trade">
                  <h6> trade2 </h6>
                </div>
                <div id="trade3" className="trade">
                  <h6> trade3 </h6>
                </div>
                <div id="trade4" className="trade">
                  <h6> trade4 </h6>
                </div>
                <div id="trade5" className="trade">
                  <h6> trade5 </h6>
                </div>
                <div id="trade6" className="trade">
                  <h6> trade6 </h6>
                </div>
              </div>
            </div>
          </div>
        </div>























      <Script
        type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"
        strategy="beforeInteractive"
      />

      <Script
        nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"
        strategy="beforeInteractive"
      />
      <Script
        src="https://unpkg.com/moralis/dist/moralis.js"
        strategy="beforeInteractive"
      />
      <Script
        src="https://github.com/WalletConnect/walletconnect-monorepo/releases/download/1.7.1/web3-provider.min.js"
        strategy="beforeInteractive"
      />





      <Head>
        <title>LetWorkBeDone</title>
        <meta name="description" content="Generated by create next app" />

        
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossOrigin="anonymous" />
  
        <link rel="stylesheet" href="https://unpkg.com/open-props"/>
        <link rel="stylesheet" href="https://unpkg.com/open-props/normalize.min.css"/>

    
        
        
        

      </Head>

    </>
  );
};

