export const blogs = [
  {
    id: 0,
    name: "Saturo Gojo",
    description: "strongest",
    title: "Jujutsu Kaisan Anime",
    slug: "",
    created_at: new Date("13/10/2024").toLocaleString(),
    link: "https://youtu.be/-FXdZ5mX_ks?si=wX8RwOXqtZOPeOyy",
    article: "",
    image: "/contents/manfromexistence.jpg",
    keywords: [],
  },
  {
    id: 1,
    name: "Sukuna",
    description: "king",
    title: "Jujutsu Kaisan Anime",
    slug: "",
    created_at: new Date("13/10/2024").toLocaleString(),
    link: "https://youtu.be/Iwpf8vSvx_I?si=UI7szHJZIiPicCDn",
    article: "",
    image: "/contents/sukuna.jpg",
    keywords: [],
  },
  {
    id: 2,
    name: "Demon Slayer",
    description: "fresh look",
    title: "Demon Slayer Anime",
    slug: "",
    created_at: new Date("13/10/2024").toLocaleString(),
    link: "https://youtu.be/wyiZWYMilgk?si=4oU_NSvVRDbg5Akj",
    article: "",
    image: "/contents/demon-slayer.jpg",
    keywords: [],
  },
  {
    id: 3,
    name: "Miles Morales",
    description: "into the spiderverse",
    title: "Spiderman",
    slug: "",
    created_at: new Date("13/10/2024").toLocaleString(),
    link: "https://youtu.be/ApXoWvfEYVU?si=R4I-dKA6Xg52U8ut",
    article: "",
    image: "/contents/miles-morales.jpg",
    keywords: [],
  },
  {
    id: 4,
    name: "Naruto",
    description: "more than a anime",
    title: "Naruto Anime",
    slug: "",
    created_at: new Date("13/10/2024").toLocaleString(),
    link: "https://youtu.be/sE2pYubPT8k?si=bqV-5lkhDjlqbT-Q",
    article: "",
    image: "/contents/jiraya-sensei-and-naruto.jpg",
    keywords: [],
  },
  {
    id: 5,
    name: "Saitama",
    description: "no limit",
    title: "OnePuchMan Anime",
    slug: "",
    created_at: new Date("13/10/2024").toLocaleString(),
    link: "https://youtu.be/VK9jVCg-ErQ?si=K-M-XUVP0XNu9_rM",
    article: "",
    image: "/contents/confuse-saitama.jpg",
    keywords: [],
  },
];

export const projects = [
  {
    id: 0,
    name: "multiverse",
    description: "...",
    title: "Multiverse",
    slug: "",
    created_at: new Date("13/10/2024").toLocaleString(),
    link: "https://youtu.be/-FXdZ5mX_ks?si=wX8RwOXqtZOPeOyy",
    article: "",
    image: "/contents/manfromexistence.jpg",
    keywords: [],
  },
  {
    id: 1,
    name: "friday",
    description: "Ai friend",
    title: "Friday",
    slug: "",
    created_at: new Date("13/10/2024").toLocaleString(),
    link: "https://youtu.be/Iwpf8vSvx_I?si=UI7szHJZIiPicCDn",
    article: "",
    image: "/contents/sukuna.jpg",
    keywords: [],
  },
  {
    id: 2,
    name: "hello",
    description: "Social Media",
    title: "Hello",
    slug: "",
    created_at: new Date("13/10/2024").toLocaleString(),
    link: "https://youtu.be/Iwpf8vSvx_I?si=UI7szHJZIiPicCDn",
    article: "",
    image: "/contents/sukuna.jpg",
    keywords: [],
  },
  {
    id: 3,
    name: "aladdin",
    description: "Ecommerse platform",
    title: "Aladdin",
    slug: "",
    created_at: new Date("13/10/2024").toLocaleString(),
    link: "https://youtu.be/Iwpf8vSvx_I?si=UI7szHJZIiPicCDn",
    article: "",
    image: "/contents/sukuna.jpg",
    keywords: [],
  },
  {
    id: 4,
    name: "dx",
    description: "Increase devlopment expreinces",
    title: "Dx",
    slug: "",
    created_at: new Date("13/10/2024").toLocaleString(),
    link: "https://youtu.be/Iwpf8vSvx_I?si=UI7szHJZIiPicCDn",
    article: "",
    image: "/contents/sukuna.jpg",
    keywords: [],
  },
  {
    id: 5,
    name: "racingroyale",
    description: "A multiplayer racing game",
    title: "RacingRoyale",
    slug: "",
    created_at: new Date("13/10/2024").toLocaleString(),
    link: "https://youtu.be/Iwpf8vSvx_I?si=UI7szHJZIiPicCDn",
    article: "",
    image: "/contents/sukuna.jpg",
    keywords: [],
  },
];

export const products = [
  {
    id: 0,
    name: "alter",
    description: "Customize things up",
    title: "Alter",
    slug: "",
    created_at: new Date("13/10/2024").toLocaleString(),
    link: "https://youtu.be/-FXdZ5mX_ks?si=wX8RwOXqtZOPeOyy",
    article: "",
    image: "/contents/manfromexistence.jpg",
    keywords: [],
  },
  {
    id: 1,
    name: "unfairgames",
    description: "Games as fair as life",
    title: "Unfairgames",
    slug: "",
    created_at: new Date("13/10/2024").toLocaleString(),
    link: "https://youtu.be/Iwpf8vSvx_I?si=UI7szHJZIiPicCDn",
    article: "",
    image: "/contents/sukuna.jpg",
    keywords: [],
  },
  {
    id: 2,
    name: "boardgames",
    description: "Play games that involes board",
    title: "Boardgames",
    slug: "",
    created_at: new Date("13/10/2024").toLocaleString(),
    link: "https://youtu.be/Iwpf8vSvx_I?si=UI7szHJZIiPicCDn",
    article: "",
    image: "/contents/sukuna.jpg",
    keywords: [],
  },
  {
    id: 3,
    name: "grimoire",
    description: "Unlock Your Creativity with powerful Media Editor & Manager",
    title: "Grimoire",
    slug: "",
    created_at: new Date("13/10/2024").toLocaleString(),
    link: "https://youtu.be/Iwpf8vSvx_I?si=UI7szHJZIiPicCDn",
    article: "",
    image: "/contents/sukuna.jpg",
    keywords: [],
  },
  {
    id: 4,
    name: "language",
    description: "Learn different languages",
    title: "Languages",
    slug: "",
    created_at: new Date("13/10/2024").toLocaleString(),
    link: "https://youtu.be/Iwpf8vSvx_I?si=UI7szHJZIiPicCDn",
    article: "",
    image: "/contents/sukuna.jpg",
    keywords: [],
  },
  {
    id: 5,
    name: "scrolls",
    description: "Unfurl Your Files Across Every Realm",
    title: "Scrolls",
    slug: "",
    created_at: new Date("13/10/2024").toLocaleString(),
    link: "https://youtu.be/Iwpf8vSvx_I?si=UI7szHJZIiPicCDn",
    article: "",
    image: "/contents/sukuna.jpg",
    keywords: [],
  },
];