blank_issues_enabled: true
contact_links:
  - name: 🆕 Create new issue
    url: https://new-issue.ant.design
    about: The issue which is not created via https://new-issue.ant.design will be closed immediately.
  - name: 🆕 创建一个新 Issue
    url: https://new-issue.ant.design
    about: ⚠️ 注意请不要使用上面的 Report a vulnerability（报告安全漏洞）来报告组件库的 bug 和特性请求，请点击右侧 Open 按钮。不是用 https://new-issue.ant.design 创建的 issue 会被机器人自动关闭。
