# All possible options and their defaults: https://github.com/zitadel/zitadel/blob/main/cmd/defaults.yaml
zitadel:

  masterkey: 'MasterkeyNeedsToHave32Characters'

  secretConfig:

    Database:
      postgres:
        User:
          # If the user doesn't exist already, it is created
          Username: 'root'
          Password: 'Secret_DB_User_Password'
        Admin:
          Username: 'root'
          Password: ''
