name: Publish npm packages

on:
  push:
    branches: [main]

jobs:
  publish-npm:
    # crates/xtask/src/publish.rs:359
    if: "startsWith(github.event.head_commit.message, 'chore: release npm packages')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/setup-node
      - uses: ./.github/actions/setup-rust
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build packages
        run: pnpx turbo@canary run build:ts

      - name: Write NPM_TOKEN
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN_ELEVATED }}" > ~/.npmrc

      - name: Publish
        run: cargo xtask workspace --publish
