name: "Next.js integration status"
author: Turbopack team
description: "Display next.js integration test failure status"

inputs:
  # Github token to use to create test report comment. If not specified, the default token will be used with username 'github-actions'
  token:
    default: ${{ github.token }}

  # The base of the test results to compare against. If not specified, will try to compare with latest main branch's test results.
  diff_base:
    default: "main"

  # Include full test failure message in the report.
  # This is currently disabled as we have too many failed test cases, causes
  # too many report comment generated.
  expand_full_result_message:
    default: "false"

runs:
  using: node16
  main: index.js
