
import Navbar from "./navbar";
import Navbar1 from "./Navbars/navbar1";
import Footer1 from '../containers/Footer/Footer';


import Link from 'next/link'
import Script from 'next/script'
import Head from 'next/head'
// import Document, { Html, Head, Main, NextScript } from 'next/document'

// opbro🎉🎉🎉🎉😎😎😎😎





export default function Layout({ children }) {
  return (
    <>

      {/* Testing🖖🖖🖖 */}
      
      
      <Script
        type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"
        strategy="beforeInteractive"
      />
      <Script
        nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"
        strategy="beforeInteractive"
      />
      
            
          {children}


      <Head>
        <title>LetWorkBeDone</title>
        <meta name="description" content="Generated by create next app" />

        <link href='https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css' rel='stylesheet' />

    
        <link rel="stylesheet" href="https://unpkg.com/open-props"/>
        <link rel="stylesheet" href="https://unpkg.com/open-props/normalize.min.css"/>
        
        

      </Head>

    </>
  );
};





//       <Script
        // type="module" src="https://cdn.jsdelivr.net/gh/Harry1o1/Demo/nextjs/education-website/assets/js/script.js"
        // strategy="beforeInteractive"
    //   />
