name: Build Templates

on:
  push:
    branches:
      - main
    paths:
      - 'templates/**'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    paths:
      - 'templates/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        template:
          - plate-template
          - plate-playground-template
    defaults:
      run:
        working-directory: templates/${{ matrix.template }}
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2.4.1
        name: Install pnpm
        with:
          version: 8.6.1
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: $(pnpm store path)
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: 📥 Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: 🏗 Build
        run: pnpm build
