export const blogs = [
  {
    id: 0,
    name: "Saturo Gojo",
    description: "strongest",
    title: "Jujutsu Kaisan Anime",
    slug: "",
    created_at: new Date("13/10/2024").toLocaleString(),
    link: "https://youtu.be/-FXdZ5mX_ks?si=wX8RwOXqtZOPeOyy",
    article: "",
    image: "/contents/manfromexistence.jpg",
    keywords: [],
  },
  {
    id: 1,
    name: "Sukuna",
    description: "king",
    title: "Jujutsu Kaisan Anime",
    slug: "",
    created_at: new Date("13/10/2024").toLocaleString(),
    link: "https://youtu.be/Iwpf8vSvx_I?si=UI7szHJZIiPicCDn",
    article: "",
    image: "/contents/sukuna.jpg",
    keywords: [],
  },
  {
    id: 2,
    name: "Demon Slayer",
    description: "fresh look",
    title: "Demon Slayer Anime",
    slug: "",
    created_at: new Date("13/10/2024").toLocaleString(),
    link: "https://youtu.be/wyiZWYMilgk?si=4oU_NSvVRDbg5Akj",
    article: "",
    image: "/contents/demon-slayer.jpg",
    keywords: [],
  },
  {
    id: 3,
    name: "Miles Morales",
    description: "into the spiderverse",
    title: "Spiderman",
    slug: "",
    created_at: new Date("13/10/2024").toLocaleString(),
    link: "https://youtu.be/ApXoWvfEYVU?si=R4I-dKA6Xg52U8ut",
    article: "",
    image: "/contents/miles-morales.jpg",
    keywords: [],
  },
  {
    id: 4,
    name: "Naruto",
    description: "more than a anime",
    title: "Naruto Anime",
    slug: "",
    created_at: new Date("13/10/2024").toLocaleString(),
    link: "https://youtu.be/sE2pYubPT8k?si=bqV-5lkhDjlqbT-Q",
    article: "",
    image: "/contents/jiraya-sensei-and-naruto.jpg",
    keywords: [],
  },
  {
    id: 5,
    name: "Saitama",
    description: "no limit",
    title: "OnePuchMan Anime",
    slug: "",
    created_at: new Date("13/10/2024").toLocaleString(),
    link: "https://youtu.be/VK9jVCg-ErQ?si=K-M-XUVP0XNu9_rM",
    article: "",
    image: "/contents/confuse-saitama.jpg",
    keywords: [],
  },
];
