# Generated by Django 3.2.9 on 2022-01-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_checklist_testing1'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='testing2',
            field=models.BooleanField(default=False),
        ),
    ]
