import Navbar1 from "./Navbar/navbar1";
import Navbar2 from "./Navbar/navbar2";
import Navbar3 from "./Navbar/navbar3";
import Navbar4 from "./Navbar/navbar4";
import Navbar5 from "./Navbar/navbar5";
import Navbar6 from "./Navbar/navbar6";
import Navbar7 from "./Navbar/navbar7";
import Navbar8 from "./Navbar/navbar8";


import Footer1 from './Footer/footer1'
import Footer2 from './Footer/footer2'


import Link from 'next/link'
import Script from 'next/script'
import Head from 'next/head'
// import Document, { Html, Head, Main, NextScript } from 'next/document'

// opbro🎉🎉🎉🎉😎😎😎😎





export default function Layout({ children }) {
  return (
    <>

        {/* Testing🖖🖖🖖 */}
        <Script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" 
          strategy="beforeInteractive"
        />

         <Script
            type="module" src='https://rawcdn.githack.com/Harry1o1/Pro-Component/8f2f7108b8742089c79a14649a98c9453581f6d8/nextjs/ux/globals.js'
            strategy = "beforeInteractive" 
        />     
        
        <Script
          type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"
          strategy="beforeInteractive"
        />
        
        <Script
          type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"
          strategy="beforeInteractive"
        />

        <Head>
            <title>Todo</title>
            <meta name="description" content="Generated by create next app" />
            
            <link rel="stylesheet" href="https://rawcdn.githack.com/Harry1o1/Pro-Component/954263aba7cb3c534a8e1305284346dfd450bec7/nextjs/styles/boostrap.css" />
            
        </Head>
      <Navbar8 />
      <div id="hero">
            {children}
      </div>
      <Footer2 />
    </>
  )
}




//  go little bro go little bro 👍👌👌
