import Head from 'next/head'
import Image from 'next/image'
import React, { useEffect, useState, createContext, useContext } from "react";
import { ethers } from "ethers"// Download 👇👇👇 ethers,Web3
import { contractABI, contractAddress } from "../utils/constants";// Transaction.json file 🗃️🗃️🗃️
declare const window: any;
declare const ethereum: any;



    const isWalletConnected = async () => {
        
        if (typeof window !== "undefined") {
            const accounts = await window.ethereum.request({  method:'eth_accounts'  })
            console.log(accounts);
            console.log('op');
            
            if (3>1) {
                console.log('True');
            } else {
                console.log('false');
                
            }
            if (!ethereum) return alert("op")
        }
    }
    
    
    
    
    
    
    
if (typeof window !== "undefined") {
        const { ethereum } = window;// We will be here🔙🔙🔙
        console.log(window.web3);
        console.log(window.ethereum);
}






// Don't know 🤔🤔🤔
const getEthereumContract = () => {
        
      const provider = new ethers.providers.Web3Provider(ethereum);
      const signer = provider.getSigner();
      const transactionsContract = new ethers.Contract(contractAddress, contractABI, signer);

    return transactionsContract;
    
    console.log({
        provider,
        signer,
        transactionsContract        
        
    });
};




    
    
const Home: React.FC = () => {
    
    const[ currentAccount, setCurrentAccount] = useState('')
    
//  Main Function 🥰🥰🥰🥰😍
    const connectWallet = async () => {
        try {
            if (!ethereum) return alert("add wallet fool")
            
            
            const accountsCreate = await window.ethereum.request({  method:'eth_requestAccounts'  })
            
            setCurrentAccount(accountsCreate[0])
            
            console.log(accountsCreate);
            
        } catch (e) {
            console.log(e);
        }
    }   
    
    
    
    return (
        
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <h1 className="title">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className="description">
          Get started by editing{' '}
          <code className="code">pages/index.tsx</code>
        </p>

        <div className="grid">
          <a href="https://nextjs.org/docs" className="card">
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className="card">
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className="card"
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className="card"
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>
      
      
      <h1 onClick={isWalletConnected}>op</h1>
      <h1 onClick={connectWallet}>Metamask login</h1>
      
      
      <footer className="footer">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className="logo">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
    )
}

export default Home
























// $$$$$$$$$$$$$$$$$$$$$$$$$$$$$ TransactionsProvider $$$$$$$$$$$$$$$$$$$$$$$$$$$$$






