import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
console.log('Hihi giving hhh');
useEffect(() => require('../babylon.js'), []);


export default function Home() {
        return (
                <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
     <h1 className="hero">Hello world!</h1>
     <Script type="text/JavaScript" src="./javascript/main.js" />
     
     
    </div>
        )
};