version: 2
updates:
- package-ecosystem: npm
  directory: "/console"
  schedule:
    interval: weekly
    time: "02:00"
  labels:
   - "npm"
   - "dependencies"
  open-pull-requests-limit: 10
  commit-message:
    prefix: chore
    include: scope
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
    time: "02:00"
  labels:
   - "gomod"
   - "dependencies"
  open-pull-requests-limit: 10
  commit-message:
    prefix: chore
    include: scope
- package-ecosystem: "docker"
  directory: "/build"
  schedule:
    interval: "weekly"
    time: "02:00"
  open-pull-requests-limit: 10
  commit-message:
    prefix: chore
    include: scope
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
    time: "02:00"
  open-pull-requests-limit: 10
  commit-message:
    prefix: chore
    include: scope
