name: "Setup Turborepo Environment"
description: "Sets up development environment for turborepo"
inputs:
  windows:
    description: 'Set to "true" if setting up for Windows'
    required: false
    default: "false"
  github-token:
    description: "GitHub token. You can pass secrets.GITHUB_TOKEN"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Setup Node"
      uses: ./.github/actions/setup-node
      with:
        extra-flags: --no-optional

    - name: "Setup Rust"
      uses: ./.github/actions/setup-rust
      with:
        windows: ${{ inputs.windows }}
        shared-cache-key: turborepo-debug-build
        cache-key: ${{ inputs.target }}
        save-cache: true
        github-token: ${{ inputs.github-token }}

    - name: "Setup capnproto"
      uses: ./.github/actions/setup-capnproto

    - name: Install Turbo globally
      shell: bash
      run: |
        VERSION=$(npm view turbo --json | jq -r '.versions | last')
        echo "Latest published version: $VERSION"
        npm i -g turbo@$VERSION
