version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: dev.Dockerfile
    container_name: jan_web
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
