# Generated by Django 3.2.9 on 2022-01-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='testing1',
            field=models.BooleanField(default=True),
        ),
    ]
