blank_issues_enabled: true
contact_links:
  - name: ❓ Questions
    url: https://github.com/zitadel/zitadel/discussions/categories/q-a
    about: Ask for help in our Q&A discussions
  - name: 💬 ZITADEL Community Chat
    url: https://zitadel.com/chat
