import Navbar1 from "./Navbar/navbar1";
import Navbar2 from "./Navbar/navbar2";


import Link from 'next/link'
import Script from 'next/script'
import Head from 'next/head'
// import Document, { Html, Head, Main, NextScript } from 'next/document'

// opbro🎉🎉🎉🎉😎😎😎😎





export default function Layout({ children }) {
  return (
    <>

        {/* Testing🖖🖖🖖 */}
        <Script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" 
          strategy="beforeInteractive"
        />
        
        <Script
          type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"
          strategy="beforeInteractive"
        />
        
        <Script
          type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"
          strategy="beforeInteractive"
        />
        <Script
          type="module" src="https://rawcdn.githack.com/Harry1o1/Pro-Component/9e3081fdbe9a0649ea79447f702d2bb358c1bfdd/nextjs/ux/globals.js" 
          strategy="beforeInteractive"
        />

        
        <Navbar2 />
        {/* Page content */}
        <main>
            {children}
            
        </main>    
        {/* Sometimes not needed */}
        <footer>
            <h1>I amma footer</h1>
        </footer>
        

        <Head>
            <title>Todo</title>
            <meta name="description" content="Generated by create next app" />
            
            <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" />
            
            
        </Head>
        
    </>
  );
};


