name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 1 * * *' # Runs every day at 01:00
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@1.4.0
        with:
          comment_tag_name: "BLOG-POST-LIST"
          commit_message: ":memo: Updated README with the latest Feedburner blog post"
          feed_list: 'https://feeds.feedburner.com/darkwood-fr/blog,https://feeds.feedburner.com/uniflow-io/blog'
