name: Mentions workflow

on:
  issues:
    types:
      - closed
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-mentions:
    name: Update this repo's README with mentions
    runs-on: ubuntu-latest

    if: github.event.issue.title == 'Add a new mention to README.md'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16"

      - name: Update README.md file
        run: node mentions.js
